[package]
name = "aha-model-response-wrapper"
version = "0.1.0"
edition = "2024"

[dependencies]
aiway-plugin = "0.1.0"
serde_json = "1.0"
base64 = "0.22"

[lib]
name = "aha_model_response_wrapper_plugin"
crate-type = ["cdylib"]
path = "src/lib.rs"