[package]
name = "echo"
version = "0.1.0"
edition = "2024"

[dependencies]
plugin = { git = "https://github.com/xgpxg/aiway",features = ["stream"] }

[lib]
name = "echo"
crate-type = ["cdylib"]
path = "src/lib.rs"