[package]
name = "demo"
version = "0.1.0"
edition = "2024"

[dependencies]
plugin = { path = "../../lib/plugin" }
protocol = { path = "../../lib/protocol" }

[lib]
name = "demo_plugin"
crate-type = ["cdylib"]
path = "src/lib.rs"