[package]
name = "demo"
version = "0.1.0"
edition = "2024"

[dependencies]
plugin = { git = "https://github.com/xgpxg/aiway" }
protocol = { git = "https://github.com/xgpxg/aiway" }

[lib]
name = "demo_plugin"
crate-type = ["cdylib"]
path = "src/lib.rs"